# You can specify a custom resource pack and turn off forcing the pack onto non-exempt players.
resource-pack:
  force: true
  custom:
    use: false
    url: ""
    sha1: ""  # You can use https://emn178.github.io/online-tools/sha1_checksum.html or a CLI-Tool to obtain the sha1-checksum.

# Set a channel-id and send to true, if you want to announce a death on a discord channel.
spicord:
  send: false
  message_channel_id: ""

announce:
  death:
    discord: false
    chat: true
  totem:
    discord: false
    chat: true

enable_on_non_hc: false
easy_disable: false

### DO NOT CHANGE CONFIG VERSION! ###
config_version: 5
